# Generated by Django 5.2 on 2025-04-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='name',
            new_name='brand',
        ),
    ]
